### ISSUE TITLE
How to add children tasks

### ISSUE THREAD

**Issue by muralikodali** [jrupac/tasky#29]
$ **tasky -a --tasklist 1 --title "Pay my phone bill" --parent 1**

above command is giving output:

Traceback (most recent call last):
  File "/home/murali/bin/tasky", line 536, in <module>
    main(sys.argv)
  File "/home/murali/bin/tasky", line 512, in main
    tasky.HandleInputArgs()
  File "/home/murali/bin/tasky", line 402, in HandleInputArgs
    self.AddTask(task)
  File "/home/murali/bin/tasky", line 171, in AddTask
    parent = tasklist.keys()[task['parent']]
TypeError: list indices must be integers, not str

**Comment by jrupac** [comment]
Thanks - this was a bug. Should be fixed now.
